apiVersion: v1
items:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: apache-cronjob
  spec:
    concurrencyPolicy: Allow
    failedJobsHistoryLimit: 1
    jobTemplate:
      metadata:
      spec:
        template:
          metadata:
          spec:
            containers:
            - args:
              image: imageregistry.fnal.gov:443/sds/fetch-crl:latest
              name: apachecj
              args:
                - /bin/sh
                - apachectl -k restart
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
              - mountPath: /sys/fs/cgroup
                name: apachecj-1
              - mountPath: /etc/grid-security
                name: grid-security
            dnsPolicy: ClusterFirst
            restartPolicy: OnFailure
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
            volumes:
            - emptyDir: {}
              name: apachecj-1
            - name: grid-security
              persistentVolumeClaim:
                claimName: grid-security
    schedule: 0 */3 * * *
    successfulJobsHistoryLimit: 3
    suspend: false
  status:
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
