apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"image.openshift.io/v1","kind":"ImageStream","metadata":{"annotations":{"openshift.io/image.dockerRepositoryCheck":"2020-05-29T21:34:07Z"},"creationTimestamp":"2020-05-29T21:34:07Z","generation":1,"name":"fetch-crl","namespace":"fts3","resourceVersion":"118567773","selfLink":"/apis/image.openshift.io/v1/namespaces/fts3/imagestreams/fetch-crl","uid":"207f3e72-a1f4-11ea-9927-0025905c2a76"},"spec":{"lookupPolicy":{"local":false},"tags":[{"annotations":null,"from":{"kind":"DockerImage","name":"imageregistry.fnal.gov:443/sds/fetch-crl:latest"},"generation":1,"importPolicy":{},"name":"latest","referencePolicy":{"type":"Source"}}]},"status":{"dockerImageRepository":"docker-registry.default.svc:5000/fts3/fetch-crl","tags":[{"items":[{"created":"2020-05-29T21:34:07Z","dockerImageReference":"imageregistry.fnal.gov:443/sds/fetch-crl@sha256:c98baabbfdc92362f52701e6742e07a8faedda68d1824ebef393b89a396a9f56","generation":1,"image":"sha256:c98baabbfdc92362f52701e6742e07a8faedda68d1824ebef393b89a396a9f56"}],"tag":"latest"}]}}
      openshift.io/image.dockerRepositoryCheck: 2020-05-29T21:34:07Z
    creationTimestamp: 2020-05-29T21:34:07Z
    generation: 1
    name: fetch-crl
    namespace: fts3
    resourceVersion: "189926652"
    selfLink: /apis/image.openshift.io/v1/namespaces/fts3/imagestreams/fetch-crl
    uid: 207f3e72-a1f4-11ea-9927-0025905c2a76
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: imageregistry.fnal.gov:443/sds/fetch-crl:latest
      generation: 1
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: docker-registry.default.svc:5000/fts3/fetch-crl
    tags:
    - items:
      - created: 2020-05-29T21:34:07Z
        dockerImageReference: imageregistry.fnal.gov:443/sds/fetch-crl@sha256:c98baabbfdc92362f52701e6742e07a8faedda68d1824ebef393b89a396a9f56
        generation: 1
        image: sha256:c98baabbfdc92362f52701e6742e07a8faedda68d1824ebef393b89a396a9f56
      tag: latest
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: 2021-01-21T19:52:32Z
    creationTimestamp: 2020-05-29T21:33:59Z
    generation: 3
    name: fts3
    namespace: fts3
    resourceVersion: "189946560"
    selfLink: /apis/image.openshift.io/v1/namespaces/fts3/imagestreams/fts3
    uid: 1b4e4d9b-a1f4-11ea-9927-0025905c2a76
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: imageregistry.fnal.gov/sds/fts3:3.11
      generation: 3
      importPolicy: {}
      name: "3.11"
      referencePolicy:
        type: Source
    - annotations: null
      from:
        kind: DockerImage
        name: imageregistry.fnal.gov:443/sds/fts3:latest
      generation: 1
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: docker-registry.default.svc:5000/fts3/fts3
    tags:
    - items:
      - created: 2021-01-21T19:52:32Z
        dockerImageReference: imageregistry.fnal.gov/sds/fts3@sha256:66f24e1ec691f5a05d3770ee70f919dbb02281f49d0ac830cab0393ea191f9bb
        generation: 3
        image: sha256:66f24e1ec691f5a05d3770ee70f919dbb02281f49d0ac830cab0393ea191f9bb
      tag: "3.11"
    - items:
      - created: 2020-05-29T21:33:59Z
        dockerImageReference: imageregistry.fnal.gov:443/sds/fts3@sha256:18958f81515ba30fb3dc08f1e264a970ab46a07389542595ede3ab06e09aceb6
        generation: 1
        image: sha256:18958f81515ba30fb3dc08f1e264a970ab46a07389542595ede3ab06e09aceb6
      tag: latest
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
