apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: fts3db
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: grid-security
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
  status:
    capacity:
      storage: 1Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
