apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: fts3db
  spec:
    ports:
    - name: mariadb
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      name: fts3db
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ftscontainers
    name: ftscontainers
  spec:
    externalIPs:
    - 131.225.218.140
    ports:
    - name: port-1
      port: 8446
      protocol: TCP
      targetPort: 8446
    - name: port-2
      port: 8449
      protocol: TCP
      targetPort: 8449
    selector:
      app: ftscontainers
      deploymentconfig: ftscontainers
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""