apiVersion: v1
items:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    creationTimestamp: 2019-08-27T19:14:04Z
    name: fetch-crl-cron
  spec:
    concurrencyPolicy: Allow
    failedJobsHistoryLimit: 1
    jobTemplate:
      metadata:
        creationTimestamp: null
      spec:
        template:
          metadata:
            creationTimestamp: null
          spec:
          - args:
            containers:
              image: imageregistry.fnal.gov:443/sds/fetch-crl:latest
              imagePullPolicy: Always
              name: fetch-crl
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
              - mountPath: /sys/fs/cgroup
                name: fetch-crl-1
              - mountPath: /etc/grid-security
                name: grid-security
            dnsPolicy: ClusterFirst
            restartPolicy: OnFailure
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
            volumes:
            - emptyDir: {}
              name: fetch-crl-1
            - name: grid-security
              persistentVolumeClaim:
                claimName: grid-security
    schedule: 0 */3 * * *
    successfulJobsHistoryLimit: 3
    suspend: false
  status:
    lastScheduleTime: 2019-11-27T15:00:00Z
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
