apiVersion: v1
items:

- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ftscontainers
    name: ftscontainers
  spec:
    replicas: 1
    selector:
      app: ftscontainers
      deploymentconfig: ftscontainers
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: ftscontainers
          deploymentconfig: ftscontainers
      spec:
        initContainers:
        - name: fetch-crls-first-time
          image: imageregistry.fnal.gov:443/sds/fetch-crl:latest
          command: ['bash', '-c', 'find /etc/grid-security/certificates/ -mindepth 1 | read || (osg-ca-manage setupca --location root --url osg --verbose ; fetch-crl --verbose)']
          volumeMounts:
          - mountPath: /etc/grid-security
            name: grid-security-external
        containers:
        - env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: fts3physicaldb
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: fts3physicaldb
          - name: WEB_INTERFACE
            value: fts-dev.fnal.gov
          - name: DATABASE_UPGRADE
            value: "yes"
          image: imageregistry.fnal.gov:443/sds/fts3:latest
          imagePullPolicy: Always
          name: ftscontainers
          ports:
          - containerPort: 8446
            protocol: TCP
          - containerPort: 8449
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - mysql -h mariadb-dev01.fnal.gov -P 3314 -u $MYSQL_USER --password="$MYSQL_PASSWORD"
                -e 'SELECT 1'
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
          - mountPath: /sys/fs/cgroup
            name: ftscontainers-volume-1
          - mountPath: /tmp/fts3-configs
            name: volume-6pk0d
            readOnly: true
          - mountPath: /tmp/fts3-host-pems
            name: volume-0iqzh
            readOnly: true
          - mountPath: /etc/grid-security-external
            name: grid-security-external
        restartPolicy: Always
        serviceAccount: useroot
        serviceAccountName: useroot

        volumes:
        - emptyDir: {}
          name: ftscontainers-volume-1
        - name: volume-6pk0d
          secret:
            defaultMode: 420
            secretName: fts3-configs
        - name: volume-0iqzh
          secret:
            defaultMode: 420
            secretName: fts3-host-pems
        - name: grid-security-external
          persistentVolumeClaim:
            claimName: grid-security
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ftscontainers
        from:
          kind: ImageStreamTag
          name: fts3:latest
      type: ImageChange
    replicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
