apiVersion: v1
items:

- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: fts3containers
    name: fts3containers
  spec:
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
    replicas: 1
    selector:
      app: fts3containers
      deploymentconfig: fts3containers
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: fts3containers
          deploymentconfig: fts3containers
      spec:
        initContainers:
        - name: fetch-crls-first-time
          image: imageregistry.fnal.gov:443/sds/fetch-crl:latest
          command: ['bash', '-c', 'find /etc/grid-security/certificates/ -mindepth 1 | read || (osg-ca-manage setupca --location root --url osg --verbose ; fetch-crl --verbose)']
          volumeMounts:
          - mountPath: /etc/grid-security
            name: grid-security-external
        containers:
        - env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: fts3physicaldb
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: fts3physicaldb
          - name: WEB_INTERFACE
            value: fts3-public.fnal.gov
          #- name: DATABASE_UPGRADE
          #  value: "yes"
          image: imageregistry.fnal.gov:443/sds/fts3:3.12.5
          imagePullPolicy: Always
          name: fts3containers
          ports:
          - containerPort: 8446
            protocol: TCP
          - containerPort: 8449
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - mysql -h mariadb-prd03.fnal.gov -P 3314 -u $MYSQL_USER --password="$MYSQL_PASSWORD"
                -e 'SELECT 1'
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
          - mountPath: /sys/fs/cgroup
            name: fts3containers-volume-1
          - mountPath: /tmp/fts3-configs
            name: volume-6pk0d
            readOnly: true
          - mountPath: /tmp/fts3-host-pems
            name: volume-0iqzh
            readOnly: true
          - mountPath: /etc/grid-security-external
            name: grid-security-external
        restartPolicy: Always
        serviceAccount: useroot
        serviceAccountName: useroot

        volumes:
        - emptyDir: {}
          name: fts3containers-volume-1
        - name: volume-6pk0d
          secret:
            defaultMode: 420
            secretName: fts3-configs
        - name: volume-0iqzh
          secret:
            defaultMode: 420
            secretName: fts3-host-pems
        - name: grid-security-external
          persistentVolumeClaim:
            claimName: grid-security
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - fts3containers
        from:
          kind: ImageStreamTag
          name: fts3:3.12.5
      type: ImageChange
    replicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
