apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: 2020-05-29T21:34:07Z
    creationTimestamp: 2020-05-29T21:34:07Z
    generation: 1
    name: fetch-crl
    namespace: fts3
    resourceVersion: "118567773"
    selfLink: /apis/image.openshift.io/v1/namespaces/fts3/imagestreams/fetch-crl
    uid: 207f3e72-a1f4-11ea-9927-0025905c2a76
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: imageregistry.fnal.gov:443/sds/fetch-crl:latest
      generation: 1
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: docker-registry.default.svc:5000/fts3/fetch-crl
    tags:
    - items:
      - created: 2020-05-29T21:34:07Z
        dockerImageReference: imageregistry.fnal.gov:443/sds/fetch-crl@sha256:c98baabbfdc92362f52701e6742e07a8faedda68d1824ebef393b89a396a9f56
        generation: 1
        image: sha256:c98baabbfdc92362f52701e6742e07a8faedda68d1824ebef393b89a396a9f56
      tag: latest
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: 2020-05-29T21:33:59Z
    creationTimestamp: 2020-05-29T21:33:59Z
    generation: 1
    name: fts3
    namespace: fts3
    resourceVersion: "118567745"
    selfLink: /apis/image.openshift.io/v1/namespaces/fts3/imagestreams/fts3
    uid: 1b4e4d9b-a1f4-11ea-9927-0025905c2a76
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: imageregistry.fnal.gov:443/sds/fts3:latest
      generation: 1
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: docker-registry.default.svc:5000/fts3/fts3
    tags:
    - items:
      - created: 2020-05-29T21:33:59Z
        dockerImageReference: imageregistry.fnal.gov:443/sds/fts3@sha256:18958f81515ba30fb3dc08f1e264a970ab46a07389542595ede3ab06e09aceb6
        generation: 1
        image: sha256:18958f81515ba30fb3dc08f1e264a970ab46a07389542595ede3ab06e09aceb6
      tag: latest
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
